/* Adform Asynchronous Script Loader */
(function(k){function w(a,c,b){b||(b=c,c=[]);a in f&&f[a]&&(f[a]=!1,p--);n(c,function(){try{h[a]=b.apply(null,arguments)}finally{delete f[a],q()}});p&&"$ignore"!=a||(0>m&&(m=!1),q())}function n(a,c){for(var b=0,e=a.length,g,f=[];b<e;b++)if(g=a[b],g in h)f[b]=h[g];else{l.push(arguments);m||(m=r(x,0));return}try{c.apply(null,f)}catch(d){s(d)}}function q(){var a=l,c=0,b=a.length;for(l=[];c<b;c++)n.apply(null,a[c])}function x(){var a=f,c=l.length,b=[],e,g,d;for(f={};c--;)for(e=l[c][0],g=e.length;g--;){d=
e[g];if(d in a){s(Error('Module "'+d+'" is missing'));l.splice(c,1);break}d in h||e[g]in f||(b.push(e[g]),f[e[g]]=!0,p++)}b.length&&(m=-1,a=t.createElement("script"),a.async=a.defer=!0,a.src=y+"//s2.adform.net/stoat/416/s2.adform.net/load/v/0.0.16/e/"+h.$env.$hash()+"/i/"+h.$ignore+"/r:"+b.sort().join(":"),b=t.getElementsByTagName("script")[0],b.parentNode.insertBefore(a,b))}function s(a){r(function(){throw a;},0)}function u(){for(var a=arguments,c=0,b=a.length,e=[];c<b;c++)z(a[c])||e.push(a[c]);return e.length?v.apply(d,e):d.length}
function z(a){function c(b){b.apply(null,a.slice(1))}var b=a[0],d=h[b];d?c(d):n([b],c)}var d=k["_adfq"]||(k["_adfq"]=[]),t=k.document,y="https:"===k.location.protocol?"https:":"http:",h={require:n,$boot:{window:k}},l=[],f={},p=0,v,m,r=k.setTimeout;(function(){var a;v=d.push;d.define=w;d.push=u;a=d.slice();d.length=0;u.apply(d,a)})()})(window);
_adfq.define("$env",["$boot"],function(P){function w(){function m(b,x){var a=x.charAt(0).toUpperCase()+x.slice(1);return f(b,x,"ms"+a,"moz"+a,"webkit"+a)}function f(b){for(var a=arguments,c=a.length;--c;)if(a[c]in b)return a[c]}function d(a,b){return 0<=(""+a).toLowerCase().indexOf(b.toLowerCase())}var b=P.window,c=b.document,e=c.documentElement,n=b.navigator,g=b.parent,h=n.vendor,a=n.userAgent,q=b.Adform||{},r=c.createElement("div"),s=function(a){for(var b=[!0],c=a.top,d;a!=c;){try{d=!!(a=a.parent).Image}catch(e){d=
!1}b.push(d)}return b}(b),g=b!=g,l=!g||s[1],y=!g||s[s.length-1],p=function(){var a=n.plugins,c=n.mimeTypes,a=a&&a["Shockwave Flash"]&&(c&&c["application/x-shockwave-flash"]&&c["application/x-shockwave-flash"].enabledPlugin||a["Shockwave Flash"]).description||"",c=!a&&b.ActiveXObject,d=16,e;if(c)for(;5<=d--&&!a;)try{e=new c("ShockwaveFlash.ShockwaveFlash."+d);6===d&&(e.AllowScriptAccess="always",a="WIN 6.0.21.0");try{a=e.GetVariable("$version").replace(/,/i,".")}catch(f){}}catch(g){}return parseFloat(a.replace(/^.*?(\d+[.,].*)/,
"$1"))||0}(),E=10.3<=p&&!y,F=m(c,"hidden"),G=!!F,t=/MSIE|Trident/i.test(a),w=t&&("Microsoft Internet Explorer"===n.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))?parseFloat(RegExp.$1):-1,r=f(r,"addEventListener"),u=d(h,"apple computer"),z=d(a,"ipad"),A=d(a,"iphone"),v=z||A,k;k=v&&(k=/\sos\s(\d+)_\d+/i.exec(a))&&(k=4<k[1]>>0);var B=d(h,"google"),H=!v&&d(a,"android"),I="ontouchstart"in c||"ontouchstart"in b,J=(u||B)&&/(chrome|crios)+\/[\d\.]+\s/i.test(a),K=/Firefox\/[\d\.]+/i.test(a),
C=d(a,"opera"),h=C&&d(a,"opr")&&d(h,"opera software"),D=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&u,a=t&&(d(a,"IEMobile")||d(a,"WPDesktop")),L=D&&!("webkitRequestAnimationFrame"in b),M="screenX"in b,N="outerWidth"in b,O="mozInnerScreenX"in b,e=e.msContentZoomFactor,c=c.fireEvent&&c.attachEvent,Q=m(b,"requestAnimationFrame"),q=q.ADFIframe;return{result:[g,l,y,E,G,t,r,u,z,A,v,k,B,H,I,J,K,C,h,D,a,L,M,N,O,e,c,q],exports:{nop:function(){},access:s,frame:g,accParent:l,accTop:y,flashVersion:p,
flInScreen:E,hidden:F,hasHidden:G,isIE:t,ieVersion:w,addEvent:r,isApple:u,isIPad:z,isIPhone:A,isIOS:v,isIOSF:k,isGoogle:B,isAndroid:H,isTouch:I,isChrome:J,isFirefox:K,isOpera:C,isOperaWebkit:h,isSafari:D,isIEMobile:a,isSafari5OrLess:L,screenX:M,outerWidth:N,mozInnerScreenX:O,msZF:e,ieDomEvents:c,reqAni:Q,adfFrm:q}}}var p={$hash:function(){if(!l){for(var m=[],f=w(),d=f.result,f=f.exports,b=0,c=d.length,e=0,c=c+(6-c%6)%6;b<c;b++)e=e<<1|!!d[b],5==b%6&&(m.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(e)),
e=0);for(b in f)p[b]=f[b];l=m.join("")}return l}},l;return p});
_adfq.define("$ignore",function(){return"wAAA";});